# emotes.py

EMOTE_DICT = {
    # Dances
    "dance": "emote-dance",
    "macarena": "emote-macarena",
    "shuffle": "emote-shuffle",
    "floss": "dance-floss",
    "robot": "emote-robot",
    "disco": "emote-disco",
    "salsa": "emote-salsa",
    "twerk": "dance-twerk",
    "griddy": "dance-griddy",
    "freshstep": "emote-freshstep",
    "russian": "emote-russiandance",
    "gangnam": "emote-gangnam",
    
    # Social & Actions
    "wave": "emote-wave",
    "hello": "emote-hello",
    "salute": "emote-salute",
    "kiss": "emote-kiss",
    "hug": "emote-hug",
    "thumbsup": "emote-thumbsup",
    "peace": "emote-peace",
    "sit": "emote-sit",
    "sleep": "emote-sleep",
    "laugh": "emote-laughing",
    "cry": "emote-cry",
    "angry": "emote-angry",
    "think": "emote-think",
    "wink": "emote-wink",
    "propose": "emote-propose",
    "pushups": "emote-pushups",
    
    # Special, Ghost & Space
    "astronaut": "emote-astronaut",
    "space": "idle-space",
    "teleport": "emote-teleporting",
    "levitate": "emote-levitate",
    "ghost": "emote-ghost-idle",
    "ghostfloat": "emote-ghost-idle", 
    "laid": "sit-idle-laidback",
    "relaxing": "emote-relaxed",
    "zombie": "emote-zombie-crawl",
    "backflip": "emote-backflip",
    "cartwheel": "emote-cartwheel",
    "ninja": "emote-ninja",
    "sword": "emote-sword",
    "magic": "emote-magic",
    "swag": "dance-swagbounce",
    "kisses": "emote-blowkisses",
    "twerk": "dance-twerk",
    "mine": "dance-mine",
    "true" : "dance-true-heart",
    "pv" : "dance-popularvibe",
    "laid" : "sit-idle-laidBack",
    "relaxing" : "emote-relaxed",
    "rest" : "sit-idle-cute",
    "woah" : "dance-woah",
    "cozy" : "idle-floorsleeping",
    "cozy2" : "idle-floorsleeping2",
    "smooch": "emote-kissing",
    "star": "emote-threadexchange-star",
    "enthus": "idle-enthusiastic",
    "repose": "sit-relaxed",
    "attentive": "idle-layingdown",
    "spider": "emote-spiderman",
}
